export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE'
export const ADD_PROJECT_STARTED = 'ADD_PROJECT_STARTED'
export const DELETE_PROJECT = 'DELETE_PROJECT'
